name: Keep n8n Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
jobs:
  ping-n8n:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n
        run: curl -s https://your-n8n-app.onrender.com/healthz > /dev/null
